services:
  - type: web
    name: monad-run-chat
    env: node
    buildCommand: npm install
    startCommand: ts-node server/websocket.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "3001"

databases:
  - name: monad-run-db
    databaseName: monad_run
    user: monad_run_user
    plan: free 