services:
  - type: web
    name: monad-run-chat
    env: node
    buildCommand: npm ci
    startCommand: npx ts-node server/websocket.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_F45rEmpjUNkc@ep-polished-field-a5eosskn-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: PORT
        value: "3001"

databases:
  - name: monad-run-db
    databaseName: monad_run
    user: monad_run_user
    plan: free 